# Generated by Django 2.2.2 on 2019-06-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Автор книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='full_title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Полное название книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='short_title',
            field=models.CharField(max_length=255, verbose_name='Краткое название книги'),
        ),
    ]
