# Generated by Django 2.2.2 on 2019-06-25 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Bio')),
                ('type_view', models.CharField(blank=True, choices=[('fio', 'ФИО'), ('pseudo_name', 'Псевдоним')], max_length=255, null=True, verbose_name='Тип представления')),
                ('pseudoname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Псевдоним')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
