# Generated by Django 2.2.2 on 2019-06-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('u_cabinet', '0002_booklistinbasket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booklistinbasket',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='booklistinbasket',
            old_name='user_id',
            new_name='user',
        ),
    ]
