# Generated by Django 2.2.2 on 2019-06-30 17:22

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('u_cabinet', '0003_auto_20190630_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Title')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('status', models.CharField(choices=[('publish', 'Да'), ('unpublish', 'Нет')], max_length=55, verbose_name='Publish?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_cabinet.ReviewAuthor')),
            ],
        ),
    ]
