# Generated by Django 2.2.2 on 2019-07-01 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0008_auto_20190620_1451'),
        ('u_cabinet', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='showcase.Book'),
            preserve_default=False,
        ),
    ]
